# Difficulty Level : Beginner

In [21]:
#Import the numpy package under the name np
import numpy as np


In [22]:
#Create a null vector of size 10

my_null_vector = np.zeros(10)
print(my_null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [23]:
#Create a vector with values ranging from 10 to 49

my_vector = np.arange(10,49)

In [24]:
print(my_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [25]:
my_vector2 = np.linspace(10,49,7)
print(my_vector2)

[10.  16.5 23.  29.5 36.  42.5 49. ]


In [27]:
#Find the shape of previous array in question 3

print(my_vector.shape, "my_vector shape", sep = ' = ')
print(my_vector2.shape, "my_vector 2 shape", sep = ' = ')

(39,) = my_vector shape
(7,) = my_vector 2 shape


In [28]:
#Print the type of the previous array in question 3

print(my_vector.dtype, "my_vector type", sep = ' = ')
print(my_vector2.dtype, "my_vector 2 type", sep = ' = ')

int32 = my_vector type
float64 = my_vector 2 type


In [29]:
#Print the numpy version and the configuration

print(np.version.version)
# no idea how to do configuration, online i found
#  that we can use "_version_" and "_config_" attributes to 
#  find these out but it gives me AttributeError.


1.19.4


In [30]:
print(np.__version__)

1.19.4


In [31]:
print(np.show_config())

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


In [32]:
#Print the dimension of the array in question 3


my_vector.ndim

1

In [33]:
#Create a boolean array with all the True values


my_list = [ [1,1,1,1], [1,1,1,1] , [1,1,1,1]]
my_boolean_array = np.array(my_list,dtype=bool)
my_boolean_array

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [34]:
#Create a two dimensional array

my_2D_array = np.array([1,3,5,7],ndmin=2)
my_2D_array

array([[1, 3, 5, 7]])

In [35]:
#Create a three dimensional array

my_3D_array = np.array([1,3,5,7],ndmin=3)
my_3D_array

array([[[1, 3, 5, 7]]])

# Difficulty Level : Easy

In [36]:
#Reverse a vector (first element becomes last)
my_vect = np.arange(1,10)

print(my_vect, ":" , np.flip(my_vect), sep = '  ')

print("\n")

my_vect2 = my_vect.reshape((3,3))
print( "vector = \n" , my_vect2  )
print( "reverse = \n", np.flip(my_vect2))

[1 2 3 4 5 6 7 8 9]  :  [9 8 7 6 5 4 3 2 1]


vector = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
reverse = 
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [37]:
#Create a null vector of size 10 but the fifth value which is 1
my_null = np.zeros(10)
my_null[4] = 1 
my_null

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [101]:
#Create a 3x3 identity matrix
my_id = np.identity(3)
my_id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [105]:
#Convert the data type of the given array from int to float
arr = np.array([1,2,3,4,5]) 
arr.dtype

dtype('int32')

In [40]:
arr = np.array(arr,dtype='float64')
arr.dtype

dtype('float64')

In [43]:
#Multiply arr1 with arr2
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [44]:
#Make an array by comparing both the arrays provided above
arr1>arr2

array([[ True, False,  True],
       [False,  True, False]])

In [97]:
#Extract all odd numbers from arr with values(0-9)
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
arr[1::2]

array([1, 3, 5, 7, 9])

In [100]:
#Replace all odd numbers to -1 from previous array
arr[1::2] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [52]:
#Replace the values of indexes 5,6,7 and 8 to 12
arr[5:9] = 12 
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [94]:
#Create a 2d array with 1 on the border and 0 inside
array = np.zeros((5,5))
array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [95]:
array[::4] = 1
array[::,::4] = 1
array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Difficulty : Medium


In [107]:
#Replace the value 5 to 12
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[(1,1)] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [108]:
#Convert all the values of 1st array to 64
arr2d[::,::] = 64
arr2d

array([[64, 64, 64],
       [64, 64, 64],
       [64, 64, 64]])

In [58]:
#Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it
twoDarray0 = np.random.randint(0,9, (3,3))
twoDarray0

array([[3, 8, 8],
       [5, 0, 4],
       [2, 8, 0]])

In [109]:
twoDarray0[0]

array([3, 8, 8])

In [60]:
#Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it
twoDarray = np.random.randint(0,9, (3,3))


In [61]:
twoDarray

array([[0, 1, 6],
       [7, 0, 6],
       [0, 8, 5]])

In [62]:
twoDarray[1,1]

0

In [63]:
#Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows
twoDarray2 = np.random.randint(0,9, (3,3))

twoDarray2

array([[5, 8, 5],
       [3, 8, 1],
       [3, 6, 8]])

In [110]:
twoDarray2[0:2,2]

array([5, 1])

In [112]:
#Create a 10x10 array with random values and find the minimum and maximum values

random_array = np.random.randint(-100,100, (10,10))
min = random_array.min()
max = random_array.max()

print('min = ', min )
print('max = ', max )

min =  -98
max =  99


In [114]:
#Find the common items between a and b

a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
a[a==b]

array([2, 2, 4, 4])

In [118]:
#Find the positions where elements of a and b match
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [170]:
#Find all the values from array data where the values from array names are not equal to Will

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

In [73]:
ans = np.where(names != 'Will')
print(ans)
data[ans]

(array([0, 1, 3, 5, 6], dtype=int64),)


array([[ 0.98308585,  0.90540172,  0.86536911,  0.48450493],
       [ 1.27932097,  0.40290221, -0.20098742, -0.06128922],
       [ 1.05391093, -1.66610668,  2.78035417,  0.69637345],
       [ 0.6445215 , -1.52479523,  0.11949437, -0.49053238],
       [ 0.91614461,  0.74383662, -0.67519227,  0.58655204]])

In [179]:
#Find all the values from array data where the values from array names are not equal to Will and Joe

#01:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

ans2a = np.where(names != 'Will')
ans2b = np.where(names != 'Joe')
ans2 = np.intersect1d(ans2a, ans2b)
print(ans2)
data[ans2]

[0 3]


array([[-0.11560528,  0.9829581 , -0.05898578, -1.84626928],
       [ 0.34680357, -0.29888519, -0.50313389,  1.32030237]])

In [180]:
#02:
ans3 = (names != 'Will') & (names != 'Joe')
data[ans3]

array([[-0.11560528,  0.9829581 , -0.05898578, -1.84626928],
       [ 0.34680357, -0.29888519, -0.50313389,  1.32030237]])

In [182]:
#03:
a = names=='Will'
b = names=='Joe'

names[a] = 2
names[b] = 2
print(names)

data[names!='2']

['Bob' '2' '2' 'Bob' '2' '2' '2']


array([[-0.11560528,  0.9829581 , -0.05898578, -1.84626928],
       [ 0.34680357, -0.29888519, -0.50313389,  1.32030237]])

# Difficulty : Hard

In [193]:
#Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

myarr = np.array([[ 1.94,  7.96, 11.54,  6.03, 14.32],
       [ 4.65,  3.72,  4.62,  8.32, 13.89],
       [14.11,  8.61,  9.72,  1.22, 11.9 ]])
myarr

array([[ 1.94,  7.96, 11.54,  6.03, 14.32],
       [ 4.65,  3.72,  4.62,  8.32, 13.89],
       [14.11,  8.61,  9.72,  1.22, 11.9 ]])

In [202]:
#Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

#02:
myarr3 = np.array([ 1.94,  7.96, 11.54,  6.03, 14.32,  4.65,  3.72,  4.62,  8.32,
       13.89, 14.11,  8.61,  9.72,  1.22, 11.9 , 15.87])
myarr4 = myarr3.reshape((2,2,4))
myarr4

array([[[ 1.94,  7.96, 11.54,  6.03],
        [14.32,  4.65,  3.72,  4.62]],

       [[ 8.32, 13.89, 14.11,  8.61],
        [ 9.72,  1.22, 11.9 , 15.87]]])

In [206]:
#Swap axes of the array you created in Question 32

#01:
myarr4.transpose()

array([[[ 1.94,  8.32],
        [14.32,  9.72]],

       [[ 7.96, 13.89],
        [ 4.65,  1.22]],

       [[11.54, 14.11],
        [ 3.72, 11.9 ]],

       [[ 6.03,  8.61],
        [ 4.62, 15.87]]])

In [207]:
#02:
myarr4.T

array([[[ 1.94,  8.32],
        [14.32,  9.72]],

       [[ 7.96, 13.89],
        [ 4.65,  1.22]],

       [[11.54, 14.11],
        [ 3.72, 11.9 ]],

       [[ 6.03,  8.61],
        [ 4.62, 15.87]]])

In [216]:
#03:
print(myarr4, "\n")
print(myarr4.reshape((2,4,2)) ,'\n' )
print(myarr4.reshape((4,2,2)))

[[[ 1.94  7.96 11.54  6.03]
  [14.32  4.65  3.72  4.62]]

 [[ 8.32 13.89 14.11  8.61]
  [ 9.72  1.22 11.9  15.87]]] 

[[[ 1.94  7.96]
  [11.54  6.03]
  [14.32  4.65]
  [ 3.72  4.62]]

 [[ 8.32 13.89]
  [14.11  8.61]
  [ 9.72  1.22]
  [11.9  15.87]]] 

[[[ 1.94  7.96]
  [11.54  6.03]]

 [[14.32  4.65]
  [ 3.72  4.62]]

 [[ 8.32 13.89]
  [14.11  8.61]]

 [[ 9.72  1.22]
  [11.9  15.87]]]


In [220]:
#Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0
myarr5 = np.random.randint(0,20,(2,5))
print(myarr5.size)
myarr6 = np.sqrt(myarr5)
myarr7 = np.where(myarr6<0.5, 0 , myarr6)
myarr7

10


array([[3.74165739, 0.        , 4.35889894, 1.73205081, 3.74165739],
       [3.87298335, 2.44948974, 1.73205081, 3.74165739, 0.        ]])

In [223]:
#Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

myarr8 = np.random.randint(0,12,(4,4))
myarr9 = np.random.randint(0,12,(4,4))

np.maximum(myarr8,myarr9)


array([[ 9,  5, 11,  7],
       [ 5,  9,  5,  8],
       [ 1,  9,  7,  9],
       [ 7, 11,  9,  6]])

In [231]:
#Find the unique names and sort them out!

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

ans = np.unique(names)
ans.sort()
ans

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [240]:
#From array a remove all items present in array b

a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])

np.array(set(a)-set(b))

array({1, 2, 3, 4}, dtype=object)

In [327]:
#Following is the input NumPy array delete column two and insert following new column in its place.
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = np.array([[10,10,10]])


[array([[34, 43, 73],
        [82, 22, 12],
        [53, 94, 66]]),
 array([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])]

In [330]:
newColumn.shape

(1, 3)

In [329]:
sampleArray.shape

(3, 2)

In [331]:
sampleArray = sampleArray[:,:2]
print(sampleArray.shape)
sampleArray 

(3, 2)


array([[34, 43],
       [82, 22],
       [53, 94]])

In [332]:
sampleArray = np.concatenate((sampleArray,newColumn.T),axis=1)
sampleArray

array([[34, 43, 10],
       [82, 22, 10],
       [53, 94, 10]])

In [301]:
#Find the dot product of the below two matrix

x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [304]:
#Generate a matrix of 20 random values and find its cumulative sum

myarr11 = np.random.randint(-20,20,(4,5))
print(myarr11)
myarr11.cumsum()

[[ -1  -5  18  -3  17]
 [  0  -1  -8  14  -1]
 [-10  17  13  18 -11]
 [-11 -12  -5  -5  10]]


array([-1, -6, 12,  9, 26, 26, 25, 17, 31, 30, 20, 37, 50, 68, 57, 46, 34,
       29, 24, 34], dtype=int32)

# The End 