In [1]:
import numpy as np


In [2]:
myarr1 = np.arange(10)
myarr2 = myarr1.reshape(2,5)
myarr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
myarr3 = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
myarr4 = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
np.vstack((myarr3,myarr4))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
myarr5 = np.array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1]])
myarr6 = np.array([[5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
np.hstack((myarr5,myarr6))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [26]:
myarr7 = np.array([[0, 1],[2, 3], [4, 5],  [6, 7], [8, 9]])
myarr8 = myarr7.ravel()
myarr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
myarr9 = np.array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]],

       [[12, 13, 14]]])

myarr9 

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]],

       [[12, 13, 14]]])

In [35]:
myarr9 = myarr9.flatten()
myarr9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
myarr11 = np.arange(15)
myarr11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
myarr11.reshape((5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [40]:
myarr12 = np.random.randint(-50,50,(5,5)) 
myarr12**2

array([[ 361,   64, 1089, 1225, 1225],
       [ 400,  841, 2025,   64,  361],
       [ 361,  289, 1681, 1225,    1],
       [1296,   25,  841,  576, 1936],
       [1521,  729,  121, 2209,   25]], dtype=int32)

In [41]:
myarr13 = np.random.randint(-50,50,(5,6))
myarr13.mean()

4.3

In [42]:
myarr13.std()

25.957850450297304

In [44]:
np.median(myarr13)

12.5

In [46]:
print(myarr13,
       '\n')
myarr13.T

[[ 23 -14  19  37  19 -24]
 [ 14  -9  23  26 -37   3]
 [ 32  -8 -25  29 -41 -33]
 [-11  22  47 -23   2  27]
 [-47 -17  19  36  11  29]] 



array([[ 23,  14,  32, -11, -47],
       [-14,  -9,  -8,  22, -17],
       [ 19,  23, -25,  47,  19],
       [ 37,  26,  29, -23,  36],
       [ 19, -37, -41,   2,  11],
       [-24,   3, -33,  27,  29]])

In [47]:
myarr14 = np.random.randint(-50,50,(4,4))
print(myarr14)
myarr14.trace()

[[-23  -1 -50 -33]
 [-33  48 -46  -2]
 [  3 -25 -21 -18]
 [-41  42  17 -16]]


-12

In [49]:
np.linalg.det(myarr14)

114632.99999999956

In [55]:
np.percentile(myarr14,5)  #5th percentile

-47.0

In [54]:
np.percentile(myarr14,95)  #95th percentile

43.5

In [58]:
myarr15 = np.random.randint(-5,5,(4,4))
myarr15

array([[ 0, -4,  0,  2],
       [-4,  4,  1, -4],
       [ 3, -3,  4,  0],
       [-4,  0,  0, -5]])

In [65]:
(myarr15==0).any()

True